/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.mooo.pantasya.slidingpuzzle;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int app_icon=0x7f020000;
        public static final int sample_image=0x7f020001;
    }
    public static final class id {
        public static final int changeImageButton=0x7f040003;
        public static final int previewImage=0x7f040000;
        public static final int puzzleView=0x7f040005;
        public static final int shuffleButton=0x7f040004;
        public static final int sizeLabel=0x7f040001;
        public static final int sizeSeekBar=0x7f040002;
    }
    public static final class layout {
        public static final int activity_main=0x7f030000;
    }
}
